services:
  - type: web
    name: nexa-chat
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexa-redis
          property: connectionString
      - key: CLIENT_ORIGIN
        value: "*"
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
  - type: redis
    name: nexa-redis
    plan: free
    maxmemoryPolicy: noeviction

