services:
  - type: web
    name: nexa-chat
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build:client
    startCommand: npm start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexa-redis
          property: connectionString
      - key: CLIENT_ORIGIN
        value: "*"
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
  - type: redis
    name: nexa-redis
    plan: free
    maxmemoryPolicy: noeviction

